---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- __tests__/
- coverage/
- flow-coverage/
- flow-typed/
- node_modules/
